env:
  es2021: true
  node: true
extends: ['eslint:recommended', 'plugin:@typescript-eslint/recommended']
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - import
  - '@typescript-eslint'
rules:
  import/no-unresolved: error
  import/no-duplicates: off
  import/order:
    - 'warn'
    - alphabetize:
        order: asc
        caseInsensitive: false
      groups:
        - builtin
        - external
        - ['internal', 'sibling', 'parent']
        - index
        - unknown
      newlines-between: always
      pathGroups:
        - group: external
          pattern: 'react'
          position: before
        - group: internal
          pattern: '@*/**'
      pathGroupsExcludedImportTypes:
        - builtin
  no-unexpected-multiline: error
  semi: off
  sort-imports:
    - off
    - allowSeparatedGroups: true
      ignoreCase: true
      ignoreDeclarationSort: true
      ignoreMemberSort: false
  '@typescript-eslint/no-unused-vars': error
  '@typescript-eslint/consistent-type-definitions': ['error', 'interface']
  '@typescript-eslint/semi': ['error', 'always']
settings:
  'import/resolver':
    typescript: { project: './tsconfig.json' }
